/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.producer;

import java.util.Properties;

public class App {
  public static void main(String[] args) {
    Properties props = new Properties();

    props.put("bootstrap.servers", "");
  }
}
