/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafka.stream;

import java.util.Properties;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.kstream.KStream;

public class App {
  public static void main(String[] args) {
    StreamsBuilder builder = new StreamsBuilder();

    KStream<String, String> stream = builder.stream("users");

    stream.foreach(
        (key, value) -> {
          System.out.println(String.format("(DSL) Hello, %s", value));
        });

    Properties props = new Properties();

    props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "127.0.0.1:9092");
    props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
    props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG,
        Serdes.String().getClass().getName());
    props.put(StreamsConfig.APPLICATION_ID_CONFIG, "SayHello");

    KafkaStreams streams = new KafkaStreams(builder.build(), props);
    streams.start();

    Runtime.getRuntime().addShutdownHook(new Thread(streams::close));

    while (true) {
    }
  }
}
